spring:
  application:
    name: agg-springboot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tanci   #你本地的数据库用户名
    password: 219410 #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/tan_agg_benchmarks?useInformationSchema=true&characterEncoding=utf-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
        '[dialect]': org.hibernate.dialect.MySQL8Dialect

storage:
  upload-dir: ./uploads
  bib-dir: ${storage.upload-dir}/bib
  algorithm-imp-dir: ${storage.upload-dir}/algorithmImp
  metric-imp-dir: ${storage.upload-dir}/metricImp

logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
