spring:
  application:
    name: agg-springboot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tanci   #你本地的数据库用户名
    password: 219410 #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/tan_agg_benchmarks?useInformationSchema=true&characterEncoding=utf-8

# MyBatis 配置文件的路径。
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  # Mapper 文件的扫描路径，可以有多个，支持使用通配符。
  mapper-locations: classpath:mybatis/mapper/*.xml
